std_msgs/Header header
float64 x # ball pos to robot x
float64 y # ball pos to robot y
float64 dir # disired kick dir relative to robot, rad
float64 goal_x # goal pos to robot x
float64 goal_y # goal pos to robot y
float64 robot_theta_to_field # robot theta to field, rad
float64 power # disired kick range
int8 leg
int8 kick_subtype  # 0=normal, 1=freekick_power, 2=quickshot, 3=deflection
int8 kick_subtype  # 0=normal, 1=freekick_power, 2=quickshot, 3=deflection   # 0=right, 1=left
int8 kick_subtype  # 0=normal, 1=freekick_power, 2=quickshot, 3=deflection
int8 leg
int8 kick_subtype  # 0=normal, 1=freekick_power, 2=quickshot, 3=deflection
int8 kick_subtype  # 0=normal, 1=freekick_power, 2=quickshot, 3=deflection   # 0=right, 1=left
int8 kick_subtype  # 0=normal, 1=freekick_power, 2=quickshot, 3=deflection
